// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpORcQZmg_knlbM3H2Ep1g7YQ57SobY00',
    appId: '1:791002802079:web:10390d64da24a040c87faa',
    messagingSenderId: '791002802079',
    projectId: 'smarteggincubator-5ee0f',
    authDomain: 'smarteggincubator-5ee0f.firebaseapp.com',
    databaseURL: 'https://smarteggincubator-5ee0f-default-rtdb.firebaseio.com',
    storageBucket: 'smarteggincubator-5ee0f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWI-dK6JlGxpAj_TLHLYJR-y_pGATwqGQ',
    appId: '1:791002802079:android:e8109e555a51c7bfc87faa',
    messagingSenderId: '791002802079',
    projectId: 'smarteggincubator-5ee0f',
    databaseURL: 'https://smarteggincubator-5ee0f-default-rtdb.firebaseio.com',
    storageBucket: 'smarteggincubator-5ee0f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ0XN47sSucTak1nFv7vz8fT4XAP0rT5U',
    appId: '1:791002802079:ios:be80c2e91b053291c87faa',
    messagingSenderId: '791002802079',
    projectId: 'smarteggincubator-5ee0f',
    databaseURL: 'https://smarteggincubator-5ee0f-default-rtdb.firebaseio.com',
    storageBucket: 'smarteggincubator-5ee0f.firebasestorage.app',
    iosBundleId: 'com.solarhatch.mobile',
  );
}





